### PR TITLE
Small fix in README.md

### PR DESCRIPTION
**Pull request by ineiti**
Actually not sure if this is correct - but the only other occurence of `sigPk` is a `BBSPlusPublicKeyG2`. At least it looks wrong to have the `sigPk` be of type `BBSPlusSecretKey`...

### CODE REVIEW

**Comment by lovesh** [comment]
Yes, you're change is correct. 
Secondly, some of the functions shown in the readme have changed, see [this](https://github.com/docknetwork/crypto-wasm-ts/issues/33) for an example. Until this gets updated, have a look at [these tests](https://github.com/docknetwork/crypto-wasm-ts/tree/master/tests/composite-proofs).

**Review by lovesh — APPROVED** [review]

**Comment by ineiti** [comment]
@lovesh #33 is from my colleague. I told him to look at how to improve the documentation a bit... Any pointers in what you think is the most important part?

We're using the library for one of our hands-on workshops, and the library is really great - incredible work! If we can contribute with some documentation, we'd be happy.

**Comment by lovesh** [comment]
Thanks for your offer to help.
The conceptual documentation is fine. But some of the code examples are out of date so they need to be fixed by looking at the tests I mentioned before. Secondly there are some new features added like more protocols for range proofs which you can see in [these tests](https://github.com/docknetwork/crypto-wasm-ts/blob/master/tests/composite-proofs/msg-js-obj/bound-check.spec.ts) but missing in the Readme. 
The API described in the Readme is low-level and a higher level abstraction exists and is documented [here](https://github.com/docknetwork/crypto-wasm-ts/tree/master/src/anonymous-credentials) conceptually but lacks code examples which could be written referring [these tests](https://github.com/docknetwork/crypto-wasm-ts/tree/master/tests/anonymous-credentials), mostly [this one](https://github.com/docknetwork/crypto-wasm-ts/blob/master/tests/anonymous-credentials/presentation.spec.ts). If you haven't seen this abstraction, I'll suggest taking a look. Its more ergonomic than the code examples in the main Readme. 
There is support for threshold BBS/BBS+ as seen in [this test](https://github.com/docknetwork/crypto-wasm-ts/blob/master/tests/threshold-sigs.spec.ts) but missing from Readme.  
Finally, which parts have you had trouble using and think could benefit from more documentation, tests or a better API

**Comment by ineiti** [comment]
Great - thanks a lot. I'll discuss it with @lanterno and come back to you. Is there already an issue regarding documentation?

**Comment by lovesh** [comment]
Thanks. Just created [this issue](https://github.com/docknetwork/crypto-wasm-ts/issues/36). Feel free to ask any questions.

**Pull request merged**
